PresentationWithApi/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace PresentationWithApi.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

PresentationWithApi/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using PresentationWithApi.Areas.HelpPage.Models;

namespace PresentationWithApi.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

PresentationWithApi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationWithApi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

PresentationWithApi/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Web.Http;
using DAL.Models;
using DAL.Repositories;
using PresentationWithApi.Models;

namespace PresentationWithApi.Controllers
{
    [JsonCamelCaseFormat] 
    public class MessagesController : ApiController
    {
        readonly MessageRepository _repository = new MessageRepository();

        private static readonly GetMessagesSearchDto DefaultSearch = new GetMessagesSearchDto
        {
            PageIndex = 0,
            PageSize = 10
        };

        // GET api/messages?pageIndex=1&pageSize=10
        public PagedList<LogMessageDto> Get([FromUri] GetMessagesSearchDto searchDto)
        {
            searchDto = searchDto ?? DefaultSearch;

            if (searchDto.PageSize <= 0)
            {
                searchDto.PageSize = 10;
            }

            PagedList<LogMessageDto> result = _repository.GetPagedList(searchDto);
            return result;
        }
    }
}

PresentationWithApi/Views/Home/Index.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Etrel testna naloga</title>

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/loading-bar.min.css" rel="stylesheet" />
</head>
    <body data-ng-app="app">
        
        <style>
            #timeFromPicker .form-control, 
            #timeToPicker .form-control {
                padding: 0;
            }
        </style >

        <div>
            <div class="h1 container-fluid">
                <div class="container alert alert-success">
                    <span class="pull-left">Etrel test - Janez Lukan</span>
                    <span class="pull-right"><img src="~/Images/logoEtrel.png" alt="Etrel logo" /></span>
                </div>
            </div>
            <div data-ng-controller="messagesController as vm">
                <div class="container table-bordered" style="padding-right: 0px; padding-left: 0px; margin-bottom: 0px;">
                    <div class="col-md-12 bg-info" style="padding:5px;">
                        <span class="h5" style="margin-left: 15px">
                            <b>Vse postaje</b>
                        </span>
                    </div>
                    <div class="clear-fix"></div>


                    <div class="col-md-12 bg-info" style="margin-left: 0px;padding-top: 5px;padding-bottom: 5px;border: 1px;">
                        <div class="col-md-12 row">
                            <table class="col-md-12">
                                <tr class="col-md-12">
                                    <td class="col-md-4">
                                        <input type="text" class="input-sm col-md-12" style="margin-top: 2px"
                                               data-ng-model="vm.searchPhrase"
                                               data-ng-keyup="vm.search($event)"
                                               ng-update-model-on="change"
                                               ng-update-model-debounce="500"
                                               placeholder="Filter po vsebini">
                                    </td>
                                    <td class="col-md-1" style="text-align: right"><strong>Od:</strong></td>
                                    <td class="col-md-2">
                                        <div class="input-group">
                                            <input type="text" readonly="readonly" class="form-control" datepicker-popup="{{vm.datePickerFromOptions.format}}" ng-model="vm.datePickerFromOptions.dtFrom" is-open="vm.datePickerFromOptions.openedFrom" min="vm.datePickerFromOptions.minDate" max="'2015-06-22'"
                                                   close-on-date-selection="true" datepicker-options="vm.datePickerFromOptions.dateOptions" date-disabled="vm.datePickerFromOptions.disabled(date, mode)" ng-required="true"
                                                   clear-text="Bri&#353;i" toggle-weeks-text="Tedni" current-text="Danes" close-text="Zapri"
                                                   ng-change="vm.dateChanged()" />
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" ng-click="vm.datePickerFromOptions.openFrom($event)"><i class="glyphicon glyphicon-calendar"></i></button>
                                            </span>
                                        </div>
                                    </td>
                                    <td class="col-md-1">
                                        <div id="timeFromPicker" ng-model="vm.timeFromPicker" ng-change="vm.timeFromChanged($event)" style="display:inline-block; font-size: 0.8em">
                                            <timepicker style="padding: 0px" hour-step="1" minute-step="1" show-meridian="false"></timepicker>
                                        </div>
                                    </td>
                                    <td class="col-md-1" style="text-align: right"><strong>Do:</strong></td>
                                    <td class="col-md-2">
                                        <div class="input-group">
                                            <input type="text" readonly="readonly" class="form-control" datepicker-popup="{{vm.datePickerToOptions.format}}" ng-model="vm.datePickerToOptions.dtTo" is-open="vm.datePickerToOptions.openedTo" min="vm.datePickerToOptions.minDate" max="'2015-06-22'"
                                                   close-on-date-selection="true" datepicker-options="vm.datePickerToOptions.dateOptions" date-disabled="vm.datePickerToOptions.disabled(date, mode)" ng-required="true"
                                                   clear-text="Bri&#353;i" toggle-weeks-text="Tedni" current-text="Danes" close-text="Zapri"
                                                   ng-change="vm.dateChanged()" />
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" ng-click="vm.datePickerToOptions.openTo($event)"><i class="glyphicon glyphicon-calendar"></i></button>
                                            </span>
                                        </div>
                                    </td>
                                    <td class="col-md-1">
                                        <div id="timeToPicker" ng-model="vm.timeToPicker" ng-change="vm.timeToChanged($event)" style="display:inline-block;">
                                            <timepicker hour-step="1" minute-step="1" show-meridian="false"></timepicker>
                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <table class="table table-striped table-hover" style="margin-bottom: 0px">
                        <thead>
                            <tr class="info">
                                <th class="col-md-1"></th>
                                <th class="col-md-4">Izvor</th>
                                <th class="col-md-2">Čas</th>
                                <th class="col-md-5">Vsebina</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr data-ng-repeat="m in vm.pageMessages">
                                <td>
                                    <span class="center-block">
                                        <span ng-switch data-on="m.class">
                                            <img ng-switch-when="true" src='../../Images/status_ok.png'>
                                            <img ng-switch-when="false" src='../../Images/status_notOK.png'>
                                            <span ng-switch-default></span>
                                        </span>
                                    </span>
                                </td>
                                <td>
                                    {{m.stationName}} {{m.communicatorName}} <br />
                                    <span ng-hide="m.relayObject === '' || m.relayObject === null">{{m.relayObject}} / </span>
                                    <span ng-hide="m.relaySubObject === '' || m.relaySubObject === null">{{m.relaySubObject}} / </span>
                                    <span>{{m.relayDevice}}</span>
                                </td>
                                <td>{{m.timeStamp | date:'dd.MM.yyyy HH:mm:ss'}}</td>
                                <td>{{m.message}}</td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="clearfix"></div>
                    <div class="col-md-12 bg-info">
                        <div class="col-md-6">
                            <div style="margin-top: 10px; margin-bottom: 0px;"
                                 data-pagination=""
                                 class="pagination-sm"
                                 data-boundary-links="true"
                                 data-on-select-page="vm.pageChanged(page)"
                                 data-total-items="vm.messagesCount"
                                 data-num-pages="vm.numPages"
                                 data-items-per-page="vm.pageSize"
                                 data-page="vm.pageIndex"
                                 data-max-size="10"
                                 data-previous-text="&lsaquo;"
                                 data-next-text="&rsaquo;"
                                 data-first-text="&laquo;"
                                 data-last-text="&raquo;"></div>
                        </div>
                        <div class="col-md-3">
                            <div>
                                <div>
                                    <strong>
                                        Zapisov na stran
                                    </strong>
                                    <div class="btn btn-group dropup">
                                        <button type="button" class="btn btn-default">{{vm.pageSize}}</button>
                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                            <span class="caret"></span>
                                            <span class="sr-only">{{vm.pageSize}}</span>
                                        </button>
                                        <ul class="dropdown-menu" style="width: 100%; -moz-min-width: 0px; -ms-min-width: 0px; -o-min-width: 0px; -webkit-min-width: 0px; min-width: 0px;">
                                            <li role="presentation" style="width: 100%;"><a role="menuitem" data-ng-click="vm.setPageSize(10)" style="width: 100%;">10</a></li>
                                            <li role="presentation" style="width: 100%;"><a role="menuitem" data-ng-click="vm.setPageSize(20)" style="width: 100%;">20</a></li>
                                            <li role="presentation" style="width: 100%;"><a role="menuitem" data-ng-click="vm.setPageSize(50)" style="width: 100%;">50</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3" style="margin-top: 15px;">
                            <span class="pull-right" style="color: #f0ad4e">
                                <strong>
                                    Zapisov: {{vm.messagesCount}} | Strani: {{vm.numPages}}
                                </strong>
                            </span>
                        </div>
                    </div>
                </div>
                <div style="padding: 25px; margin: 25px;">
                    <span class="pull-right"><small><b>Janez Lukan (2014)</b></small></span>
                </div>
            </div>
        </div>


        <!--vendors-->
        <script src="~/Scripts/jquery-2.0.3.js"></script>
        <script src="~/Scripts/angular.js"></script>
        <script src="~/Scripts/angular-route.js"></script>
        <script src="~/Scripts/angular-sanitize.js"></script>
        <script src="~/Scripts/angular-animate.js"></script>
        <script src="~/Scripts/angular-resource.js"></script>
        <script src="~/Scripts/moment.js"></script>
        <script src="~/Scripts/bootstrap.js"></script>
        <script src="~/Scripts/ui-bootstrap-tpls-0.10.0.js"></script>
        <script src="~/Scripts/loading-bar.min.js"></script>

        <!--app-->
        <script src="~/app/app.js"></script>

        <!--controllers-->
        <script src="~/app/Controllers/messagesController.js"></script>

        <!--services-->
        <script src="~/app/Services/messagesPagedService.js"></script>
    </body>
</html>

PresentationWithApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">ASP.NET Web API</a></p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>